#!/bin/sh

#timezone & loglevel
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.ntp.server
uci add_list system.ntp.server='114.118.7.161'
uci add_list system.ntp.server='203.107.6.88'
uci set system.ntp='timeserver'
uci set system.ntp.enabled='1'
uci set system.ntp.enable_server='0'
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

#Default theme
uci set luci.main.mediaurlbase='/luci-static/bootstrap'	
uci commit luci

#Anonymous Mount
uci set fstab.@global[0].anon_mount=1
uci commit fstab

#Disable BBR
sed -i 's/net.ipv4.tcp_congestion_control=bbr/#net.ipv4.tcp_congestion_control=bbr/g' /etc/sysctl.d/12-tcp-bbr.conf

#sysctl conf
echo -e "\nnet.ipv4.tcp_max_syn_backlog=1024" >> /etc/sysctl.d/10-default.conf
echo "net.core.somaxconn=8192" >> /etc/sysctl.d/10-default.conf
echo "net.core.rmem_max=2621440" >> /etc/sysctl.d/10-default.conf
echo "net.core.wmem_max=2621440" >> /etc/sysctl.d/10-default.conf
echo "net.netfilter.nf_conntrack_expect_max=65536" >> /etc/sysctl.d/11-nf-conntrack.conf
sysctl -p
/etc/init.d/sysctl restart

#uhttpd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
uci del uhttpd.main.listen_https
uci commit uhttpd
/etc/init.d/uhttpd restart

#firewall
uci set firewall.@rule[1].enabled='0'
uci set firewall.@defaults[0].natflow='1'
uci set firewall.@defaults[0].flow_offloading='0'
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall
/etc/init.d/firewall restart

#dnsmasq & ipv6
uci set dhcp.@dnsmasq[0].quietdhcp='1'
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci set dhcp.@dnsmasq[0].sequential_ip='1'
uci set dhcp.@dnsmasq[0].nonegcache='1'
uci set dhcp.@dnsmasq[0].cachesize='3000'
uci set dhcp.lan.start='101'
uci set dhcp.lan.limit='100'
uci set dhcp.lan.leasetime='24h'
uci del dhcp.lan.dhcpv6
uci del dhcp.lan.ndp
uci set dhcp.lan.ra='server'
uci set dhcp.lan.dns_service='1'
uci add_list dhcp.lan.ra_flags='managed-config'
uci add_list dhcp.lan.ra_flags='other-config'
uci commit dhcp
uci delete network.globals.ula_prefix
uci commit network
/etc/init.d/odhcpd restart
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf
/etc/init.d/dnsmasq restart

#Net-smp-affinity
sed -i '/set_interface_core 20 "eth1"/d' /etc/hotplug.d/net/40-net-smp-affinity
sed -i 's,set_interface_core 10 "eth0",set_interface_core 8 "eth0",g' /etc/hotplug.d/net/40-net-smp-affinity

#Symbolic links
[ ! -f '/usr/bin/ip' ] && [ -f '/sbin/ip' ] && ln -sf /sbin/ip /usr/bin/ip
[ ! -f '/usr/bin/wget-ssl' ] && [ -f '/usr/bin/wget' ] && ln -sf /usr/bin/wget /usr/bin/wget-ssl

#luci cache
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
