#!/bin/sh

#timezone & loglevel
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.ntp.server
uci add_list system.ntp.server='114.118.7.161'
uci add_list system.ntp.server='203.107.6.88'
uci set system.ntp='timeserver'
uci set system.ntp.enabled='1'
uci set system.ntp.enable_server='0'
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

#Default theme
uci set luci.main.mediaurlbase='/luci-static/bootstrap'	
uci commit luci

#Disable BBR
sed -i 's/net.ipv4.tcp_congestion_control=bbr/#net.ipv4.tcp_congestion_control=bbr/g' /etc/sysctl.d/12-tcp-bbr.conf
#sys conf
echo -e "\net.ipv4.tcp_max_syn_backlog=1024" >> /etc/sysctl.d/10-default.conf
echo "net.core.somaxconn=8192" >> /etc/sysctl.d/10-default.conf
echo "net.core.rmem_max=2621440" >> /etc/sysctl.d/10-default.conf
echo "net.core.wmem_max=2621440" >> /etc/sysctl.d/10-default.conf
echo "net.netfilter.nf_conntrack_expect_max=65536" >> /etc/sysctl.d/11-nf-conntrack.conf
sysctl -p
/etc/init.d/sysctl restart

#uhttpd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
uci del uhttpd.main.listen_https
uci commit uhttpd
/etc/init.d/uhttpd restart

#SFE
sed -i '/shortcutfe/d' /usr/share/rpcd/ucode/luci
sed -i '/offloading/ a\                shortcutfe: access('\''/etc/init.d/shortcut-fe'\'') == true,' /usr/share/rpcd/ucode/luci

#firewall
[ -f '/sbin/fw4' ] && uci set firewall.@defaults[0].fullcone='1'
uci set firewall.@defaults[0].natflow='1'
uci set firewall.@defaults[0].flow_offloading='0'
uci set firewall.@defaults[0].shortcut_fe='0'
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall
service firewall restart
/etc/init.d/shortcut-fe enable 2>/dev/null
/etc/init.d/shortcut-fe start

#dnsmasq&ipv6
uci set dhcp.@dnsmasq[0].quietdhcp='1'
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci set dhcp.@dnsmasq[0].sequential_ip='1'
uci del dhcp.lan.dhcpv6
uci del dhcp.lan.ndp
uci set dhcp.lan.ra='server'
uci commit dhcp
/etc/init.d/odhcpd restart
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf
/etc/init.d/dnsmasq restart

#Symbolic links
[ ! -f '/usr/bin/ip' ] && [ -f '/sbin/ip' ] && ln -sf /sbin/ip /usr/bin/ip
[ ! -f '/usr/bin/wget-ssl' ] && [ -f '/usr/bin/wget' ] && ln -sf /usr/bin/wget /usr/bin/wget-ssl

#luci cache
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
